name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
     matrix:
       os: [ ubuntu-latest, windows-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build x64
      run: |
        GOARCH=amd64 go build -v -o dsuld-$RUNNER_ARCH-$RUNNER_OS ./dsuld/dsuld.go
        GOARCH=amd64 go build -v -o dsulc-$RUNNER_ARCH-$RUNNER_OS ./dsulc/dsulc.go
      shell: bash

    - name: Build x86
      if: matrix.os != 'macOS-latest'
      run: |
        GOARCH=386 go build -v -o dsuld-$RUNNER_ARCH-$RUNNER_OS ./dsuld/dsuld.go
        GOARCH=386 go build -v -o dsulc-$RUNNER_ARCH-$RUNNER_OS ./dsulc/dsulc.go
      shell: bash

    - name: Build arm
      if: matrix.os != 'macOS-latest'
      run: |
        GOARCH=arm go build -v -o dsuld-$RUNNER_ARCH-$RUNNER_OS ./dsuld/dsuld.go
        GOARCH=arm go build -v -o dsulc-$RUNNER_ARCH-$RUNNER_OS ./dsulc/dsulc.go
      shell: bash

    - name: Vet
      run: |
        go vet ./...
      shell: bash

    - name: Test
      run: |
        go test -v ./...
      shell: bash

    - name: Coverage
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -html=coverage.out -o coverage.html
      shell: bash

    - name: Upload coverage reports
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./coverage.*
